### ISSUE TITLE
Checklist for uploading to pypi

### ISSUE THREAD

**Issue by lee-t** [Caochris/SCOTIA#1]
In preperation for release on pypi here's a generic checklist of things to do: 

# Checklist: Initallize a package for publishing to PyPi

- [x] #13
- [x] Create: `HISTORY.md`, `LICENSE.txt`, and `setup.py` 
- [x] Update `HISTORY.md` with changes or "project start"
- [x] Commit the changes: 
```
git add HISTORY.md
git commit -m "Changelog for upcoming release 0.1.1."
```
- [x] Install `setuptools` and `twine` using `pip` if they aren't already. Create a `setup.py` in your source folder as follows (check out [setuptools docs](https://setuptools.readthedocs.io) for more detailed setup options):

		# replace:
		# <your_package> with your actual package name.
		# <you> with your name.
		# <your_email> with your public email address.
		# <your_github_repo_url> with your github project's url.
		from setuptools import setup, find_packages
		
		s = setup(
			name="<your_package>",
			version="1.0.0",
			license="<LISCENCE>",
			description="scotia",
			url='<your_github_repo_url>",
			packages=find_packages(),
			install_requires=[],
			python_requires = ">= 3.4",
			author="<you>",
			author_email="<your_email>",
			)

- [x]  Optional: Bump up the version number (and git commit) if this isn't your first release:

		git add . && git commit -m "chore: released 1.0.1" && git push

- [x]  Run `python setup.py sdist` from your source folder to generate a source distribution.
- [x]  Optional: Sign the newly generated package with your `gpg` signature:

		gpg -a --detach-sign dist/<your-package>-1.0.0.tar.gz
	
- [x] Upload your package using `twine`:

		twine upload dist/<your-package>-1.0.0.tar.gz -u <your-pypi-username> -p <your-pypi-password>
	
	If you've signed the package, then you may also add the signed .asc file as the argument like this:
	
		twine upload dist/<your-package>-1.0.0.tar.gz dist/<your-package>-1.0.0.tar.gz.asc -u <your-pypi-username> -p <your-pypi-password>

- [x] Visit <https://pypi.org/project/your_package> to verify that your package has been uploaded.
- [x] Run `pip install <your_package>` to verify the package installation using pip package manager.
- [x] Optional: Tag the commit with the new version number:

		git tag "1.0.1"
		git push --tags

**Comment by lee-t** [comment]
Checking in to see if help is needed on completing this checklist.  Might edit my post to use test.pypi.org instead of the real one.
